import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'What personal data SnackSpot stores, why, for how long, and how to exercise your GDPR rights.',
  alternates: { canonical: '/privacy' },
}

// GDPR Art. 13/14 transparency: plain-language description of processing,
// retention and data-subject rights. Keep in sync with the retention jobs in
// apps/worker and the export contents in lib/export-data.ts.
export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-lg px-4 py-6 space-y-6">
      <div>
        <h1 className="font-heading font-bold text-2xl text-snack-text">Privacy Policy</h1>
        <p className="text-sm text-snack-muted mt-1">Last updated: 12 June 2026</p>
      </div>

      <div className="card p-5 space-y-3">
        <h2 className="font-heading font-semibold text-snack-text">What we store</h2>
        <ul className="list-disc pl-5 text-sm text-snack-muted space-y-1">
          <li><strong className="text-snack-text">Account</strong> — email address, username, password (stored as an Argon2id hash, never readable), optional bio, avatar and timezone.</li>
          <li><strong className="text-snack-text">Content you create</strong> — reviews, ratings, photos, comments, likes, bites, favorites and follows.</li>
          <li><strong className="text-snack-text">Photos</strong> — uploads are re-encoded and <em>all metadata, including GPS location, is stripped</em> before they are shown to anyone.</li>
          <li><strong className="text-snack-text">Activity</strong> — badges, XP, quests, collectibles and notifications generated by your use of the app.</li>
          <li><strong className="text-snack-text">Technical</strong> — session tokens (hashed), and push subscriptions if you enable push notifications.</li>
        </ul>
        <p className="text-sm text-snack-muted">
          We do not use tracking or advertising cookies — only one functional session
          cookie to keep you logged in. We never sell your data.
        </p>
      </div>

      <div className="card p-5 space-y-3">
        <h2 className="font-heading font-semibold text-snack-text">Why we process it</h2>
        <ul className="list-disc pl-5 text-sm text-snack-muted space-y-1">
          <li>To provide the service: your account, your content, and the social feed (contract, Art. 6(1)(b) GDPR).</li>
          <li>To keep the platform safe: rate limiting, abuse reports and moderation (legitimate interest, Art. 6(1)(f)).</li>
          <li>To send optional emails and push notifications — only with your consent, configurable per category in Settings (Art. 6(1)(a)).</li>
        </ul>
      </div>

      <div className="card p-5 space-y-3">
        <h2 className="font-heading font-semibold text-snack-text">How long we keep it</h2>
        <ul className="list-disc pl-5 text-sm text-snack-muted space-y-1">
          <li><strong className="text-snack-text">Your account and content</strong> — until you delete them. Account deletion erases everything immediately, including your photos from storage.</li>
          <li><strong className="text-snack-text">Deleted reviews</strong> — restorable for 30 days, then permanently erased including photos.</li>
          <li><strong className="text-snack-text">Deleted photos and comments</strong> — erased immediately.</li>
          <li><strong className="text-snack-text">Login and password-reset tokens</strong> — until they expire; pruned daily.</li>
          <li><strong className="text-snack-text">Unused uploaded images</strong> — removed by a daily cleanup.</li>
        </ul>
      </div>

      <div className="card p-5 space-y-3">
        <h2 className="font-heading font-semibold text-snack-text">Your rights</h2>
        <ul className="list-disc pl-5 text-sm text-snack-muted space-y-1">
          <li><strong className="text-snack-text">Access &amp; portability</strong> (Art. 15/20) — download all your data as machine-readable JSON plus your photos via <Link href="/profile?tab=settings" className="text-snack-primary hover:underline">Settings → Privacy &amp; data</Link>.</li>
          <li><strong className="text-snack-text">Rectification</strong> (Art. 16) — edit your profile, reviews and preferences at any time in the app.</li>
          <li><strong className="text-snack-text">Erasure</strong> (Art. 17) — delete individual reviews, photos and comments, or your whole account via <Link href="/profile?tab=settings" className="text-snack-primary hover:underline">Settings</Link>. Deletion is real: data is removed from our database and file storage, not just hidden.</li>
          <li><strong className="text-snack-text">Withdraw consent</strong> (Art. 7) — switch off any email or push notification category in Settings.</li>
          <li><strong className="text-snack-text">Complaint</strong> (Art. 77) — you can lodge a complaint with your supervisory authority (in the Netherlands: Autoriteit Persoonsgegevens).</li>
        </ul>
      </div>

      <div className="card p-5 space-y-3">
        <h2 className="font-heading font-semibold text-snack-text">Where your data lives</h2>
        <p className="text-sm text-snack-muted">
          All data is stored on SnackSpot&apos;s own infrastructure (PostgreSQL database and
          S3-compatible object storage). Transactional email is delivered through our email
          provider, which processes your email address solely to deliver the message.
          Privacy-sensitive actions (account deletion, data exports) are recorded in an
          audit log that contains no personal data beyond an internal identifier.
        </p>
      </div>

      <div className="card p-5 space-y-3">
        <h2 className="font-heading font-semibold text-snack-text">Contact</h2>
        <p className="text-sm text-snack-muted">
          Questions about your data? Contact us at{' '}
          <a href="mailto:contact@snackspot.online" className="text-snack-primary hover:underline">
            contact@snackspot.online
          </a>.
        </p>
      </div>
    </div>
  )
}
